package com.araujoprada.hook.model;

public enum SERVICES {
    BUSINESS_SERVICE,
    UBIGEO_SERVICE,
    PEOPLE_SERVICE,
    GUS_SERVICE,
    CUSTOMER_SERVICE,
    ROUTE_SERVICE,
    LOCATION_SERVICE,
    VEHICLE_SERVICE,
    BUNDLE_SERVICE,
    DELIVERY_SERVICE
}
